version: '3.3'

volumes:
  pg_database_data:
  static:
  media:

services:
  db:
    image: postgres:14
    env_file: ./.env
    volumes:
      - pg_database_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Открываем порт PostgreSQL
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  frontend:
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/

  backend:
    depends_on:
      db:
        condition: service_healthy  # Запуск только когда db будет здоров
    build: ../backend
    env_file: ./.env
    volumes:
      - static:/backend_static
      - media:/app/media
      - ../data:/app/data  # Монтируем директорию data для доступа к ingredients.json
    restart: always

  nginx:
    image: nginx:1.25.4-alpine
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/media/
    restart: always
